- name: Install nodejs
  dnf:
    name: ['nodejs', 'npm']
- name: Install neovim
  dnf: name=neovim
- name: Install tmux
  dnf: name=tmux
- name: Install C Compiler for treesitter
  dnf: name=gcc
- name: Install stow
  dnf: name=stow
