- name: Install nodejs
  pacman:
    name: ["npm"]
  tags:
    - install
    - node
- name: Install Go
  pacman: name=go
  tags:
    - install
    - go
- name: Install zsh
  pacman: name=zsh
  tags:
    - install
    - zsh
- name: Change default shell to zsh
  shell: chsh -s $(grep '^/.*/zsh$' "/etc/shells" | tail -n 1) {{ user }}
  tags:
    - install
    - zsh
- name: Check ohmyzsh
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_stats
  become_user: "{{ user }}"
  tags:
    - install
    - zsh
- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: oh_my_stats.stat.exists == False
  become_user: "{{ user }}"
  tags:
    - install
    - zsh
- name: Install Rust
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  become_user: "{{ user }}"
  tags:
    - install
    - rust
- name: Install neovim
  pacman: name=neovim
  tags:
    - install
    - neovim
- name: Install wezterm
  pacman: name=wezterm
  tags:
    - install
    - wezterm
- name: Install C Compiler
  pacman: name=gcc
  tags:
    - install
    - c
- name: Install fzf
  pacman: name=fzf
  tags:
    - install
    - fzf
